---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: morningjuegos
spec:
  interval: 5m0s
  url: ssh://git@github.com/ryansheppard/morningjuegos
  ref:
    branch: main
  secretRef:
    name: morningjuegos
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: morningjuegos
spec:
  interval: 5m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: morningjuegos
  path: "./deployments/manifests"
  prune: true
  timeout: 1m
