version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/go:1.21.1
    working_directory: ~/projects/morningjuegos
    steps:
      - checkout
      - run:
          name: test
          command: |
            go test ./... -v -cover
      - setup_remote_docker
      - run:
          name: build
          command: |
            export IMAGE=registry.digitalocean.com/ryansheppard/morningjuegos
            docker build . -t $IMAGE:$CIRCLE_BUILD_NUM
            docker tag $IMAGE:$CIRCLE_BUILD_NUM $IMAGE:latest
      - run:
          name: push
          command: |
            export IMAGE=registry.digitalocean.com/ryansheppard/morningjuegos:
            echo $DOCKER_USER | docker login --username $DOCKER_USER --password-stdin registry.digitalocean.com
            docker push $IMAGE:$CIRCLE_BUILD_NUM
            docker push $IMAGE:latest

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          context:
            - DIGITAL_OCEAN
