apiVersion: apps/v1
kind: Deployment
metadata:
  name: morning-juegos
  labels:
    app: morning-juegos
    component: discord
spec:
  selector:
    matchLabels:
      app: morning-juegos
      component: discord
  template:
    metadata:
      labels:
        app: morning-juegos
        component: discord
    spec:
      containers:
        - name: morning-juegos
          image: registry.digitalocean.com/ryansheppard/morningjuegos:176 # {"$imagepolicy": "default:morningjuegos"}
          command:
            - "/morningjuegos"
          args:
            - "bot"
          ports:
            - containerPort: 15444
              name: prometheus
          env:
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
            - name: REDIS_DB
              value: "0"
            - name: TZ
              value: America/New_York
            - name: NATS_URL
              value: nats.default.svc.cluster.local:4222
            - name: OTEL_SERVICE_NAME
              value: "morningjuegos.bot"
          envFrom:
            - secretRef:
                name: morning-juegos
            - secretRef:
                name: honeycomb
