---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morning-juegos
  labels:
    app: morning-juegos
spec:
  selector:
    matchLabels:
      app: morning-juegos
  template:
    metadata:
      labels:
        app: morning-juegos
    spec:
      containers:
        - name: morning-juegos
          image: registry.digitalocean.com/ryansheppard/morningjuegos:6b37eb3
          imagePullPolicy: Always
          command:
            - "/morningjuegos"
          args:
            - "bot"
          env:
            - name: DB_PATH
              value: /etc/morningjuegos/db.sqlite3
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
            - name: TZ
              value: America/New_York
          envFrom:
            - secretRef:
                name: morningjuegos
          volumeMounts:
            - name: morning-juegos
              mountPath: /etc/morningjuegos
      volumes:
        - name: morning-juegos
          persistentVolumeClaim:
            claimName: morning-juegos
