apiVersion: apps/v1
kind: Deployment
metadata:
  name: morning-juegos
  labels:
    app: morning-juegos
    component: discord
spec:
  selector:
    matchLabels:
      app: morning-juegos
      component: discord
  template:
    metadata:
      labels:
        app: morning-juegos
        component: discord
    spec:
      containers:
        - name: morning-juegos
          image: registry.digitalocean.com/ryansheppard/morningjuegos:68 # {"$imagepolicy": "default:morningjuegos"}
          command:
            - "/morningjuegos"
          args:
            - "two"
          env:
            # - name: DB_PATH
            #   value: /etc/morningjuegos/db.sqlite3
            # - name: REDIS_ADDR
            #   value: redis.default.svc.cluster.local:6379
            # - name: REDIS_DB
            #   value: 0
            - name: TZ
              value: America/New_York
          envFrom:
            - secretRef:
                name: morning-juegos
