apiVersion: apps/v1
kind: Deployment
metadata:
  name: morning-juegos-worker
  labels:
    app: morning-juegos
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: morning-juegos
      component: worker
  template:
    metadata:
      labels:
        app: morning-juegos
        component: worker
    spec:
      containers:
        - name: morning-juegos
          image: registry.digitalocean.com/ryansheppard/morningjuegos:211 # {"$imagepolicy": "default:morningjuegos"}
          command:
            - "/morningjuegos"
          args:
            - "worker"
          env:
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
            - name: REDIS_DB
              value: "0"
            - name: TZ
              value: America/New_York
            - name: NATS_URL
              value: nats.default.svc.cluster.local:4222
            - name: OTEL_SERVICE_NAME
              value: "morningjuegos.worker"
            - name: COPY_PASTA_PATH
              value: "/etc/morningjuegos/copypasta.json"
          envFrom:
            - secretRef:
                name: morning-juegos
            - secretRef:
                name: honeycomb
          volumeMounts:
            - name: copypasta
              mountPath: /etc/morningjuegos
              readOnly: true
      volumes:
        - name: copypasta
          configMap:
            name: copypasta
