apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: morning-juegos-discord
  labels:
    app: morning-juegos
spec:
  selector:
    matchLabels:
      app: morning-juegos
      component: discord
  endpoints:
    - port: prom
      path: /metrics