---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: morning-juegos
spec:
  storageClassName: do-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
